Controllers/LibratController.cs
using Menaxhimi_Biblotekes.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Menaxhimi_Biblotekes.Controllers
{
    public class LibratController : Controller
    {
        // GET: LibratController
        public ActionResult Index()
        {
            List<LibratViewModel> n = new List<LibratViewModel>();
            n.Add(new LibratViewModel());
            return View(n);
        }

        // GET: LibratController/Details/5
        public ActionResult Details(int id)
        {
            LibratViewModel l = new LibratViewModel();
            l.Titulli = "Gjenerali i ushtrise se vdekur";
            l.ShtepiaBotuese = "Dukagjini";
            l.ISBN = "978231313112";
            l.VitiBotimit = 2001;
            l.Autoret = new List<AutoretViewModel>();
            return View(l);
        }

        // GET: LibratController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LibratController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LibratViewModel model)
        {
            
            try
            {
                //save to db
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LibratController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LibratController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LibratController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LibratController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/PjesmarresitController.cs
using Menaxhimi_Biblotekes.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Menaxhimi_Biblotekes.Controllers
{
    public class PjesmarresitController : Controller
    {

        // GET: PjesmarresitController
        public ActionResult SignIn()
        {
            return View();
        }

        public ActionResult ChangePassword()
        {
            return View();
        }
        // GET: PjesmarresitController/Details/5
        public ActionResult SignUp(int id)
        {
            return View();
        }

        public ActionResult Profili(PjesmarresitViewModel model)
        {
            return View(model);
        }
        /*  // GET: PjesmarresitController/Create
          public ActionResult Edit()
          {
              return View();
          }*/

        /* // POST: PjesmarresitController/Create
         [HttpPost]
         [ValidateAntiForgeryToken]
         public ActionResult Create(IFormCollection collection)
         {
             try
             {
                 return RedirectToAction(nameof(Index));
             }
             catch
             {
                 return View();
             }
         }*/

        // GET: PjesmarresitController/Edit/5
        public ActionResult Edit(PjesmarresitViewModel model)
        {
            return View(model);
        }

        [HttpPost]
        public void Save()
        {
           /* try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }*/
        }

        // POST: PjesmarresitController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: PjesmarresitController/Delete/5
        public ActionResult Delete(int id)
        {
            //Deactivate form DB
            return RedirectToAction("Index", "Home");
        }

        // POST: PjesmarresitController/Delete/5
        /* [HttpPost]
         [ValidateAntiForgeryToken]
         public ActionResult Delete(int id, IFormCollection collection)
         {
             try
             {
                 return RedirectToAction(nameof(Index));
             }
             catch
             {
                 return View();
             }
         }*/
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bibloteka</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow" style="background:#151D3B;">
            <div class="container">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Menaxhimi i biblotekes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Pjesmarresit" asp-action="Profili">Profili</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Librat" asp-action="Index">Librat</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Huazimet" asp-action="Index">Huazimet</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-light text-center" style="background-color:#151D3B">
        <div class="container">
            All rights reserved &copy; 2022 - Menaxhimi_Biblotekes - <a asp-area="" asp-controller="Home" asp-action="Index">Librat</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>